{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "traefik.fullname" . }}
  namespace: {{ template "traefik.namespace" . }}
  annotations:
    {{- with .Values.ingressRoute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
    {{- with .Values.ingressRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
  {{- range .Values.ingressRoute.entryPoints }}
  - {{ . }}
  {{- end }}
  routes:
  {{- range .Values.ingressRoute.matchRules }}
  - match: {{ .matchRule }}
    kind: Rule
    priority: {{ .priority }}
    services:
    {{- range .services }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .middlewares }}
    middlewares:
      {{- toYaml . | nindent 6 }}
    {{- end -}}
  {{- end }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
