apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmCharts: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmCharts:
# Use a Helm chart from the official Helm chart repository
- name: &name vault 
  releaseName: *name
  version: 0.27.0
  repo: https://helm.releases.hashicorp.com
  valuesFile: values.yaml
  namespace: *name 
  includeCRDs: true

namespace: *name

# Additonal resources to apply - do not worry about the order if you are using ArgoCD
resources:
- namespace.yaml
- dashboard-ingress.yaml
- eso-cluster-secret-store.yaml
# - dashboard-ingressroute.yaml 
