apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# helmCharts: https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmCharts:
- name: argo-cd 
  version: 6.6.0 
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  namespace: argo-cd
  includeCRDs: true

resources:
- namespace.yaml
- eso-dex-github-connector.yaml
- eso-private-repo.yaml

namespace: argo-cd
patches:
- path: crds-healthcheck.patch.yaml
  target:
    version: v1
    kind: ConfigMap 
    name: argocd-cm
- path: enable-helm.patch.yaml
  target:
    version: v1
    kind: ConfigMap 
    name: argocd-cm
- path: enable-dex.patch.yaml
  target:
    version: v1
    kind: ConfigMap 
    name: argocd-cm
- path: set-rbac.patch.yaml
  target:
    version: v1
    kind: ConfigMap 
    name: argocd-rbac-cm
