apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production 
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  source: 
    repoURL: https://github.com/zMynxx/turningpi2-k3s-gitops.git
    targetRevision: HEAD
    path: charts/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
