apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-github
  namespace: argocd

  # labels and annotations are copied over to the
  # secret that will be created
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: github-connector
    creationPolicy: Owner

  ## You can get all of the secret content (recommended)
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/git/github/dex
        metadataPolicy: None
