apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-lapi
  namespace: crowdsec
spec:
  template:
    spec:
      containers:
      - env:
        - name: LOCAL_API_URL
          value: http://crowdsec-service.crowdsec.svc.cluster.local:8080
        - name: DISABLE_AGENT
          value: "false"
