---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-production 
  namespace: cert-manager
spec:
  secretName: letsencrypt-production 
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.tpi2.local"
  dnsNames:
  - "tpi2.local"
  - "*.tpi2.local"
