apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret 
  namespace: longhorn
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-cluster-store 
    kind: ClusterSecretStore
  target:
    name: aws-secret
    creationPolicy: Owner

  ## You can get all of the secret content (recommended)
  dataFrom:
  - extract:
      key: secret/minio/longhorn/aws-secret
