apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-applicationset 
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: &repo git@github.com:zMynxx/turningpi2-k3s-gitops.git 
        revision: HEAD
        directories:
          - path: kustomize/*
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
      # annotations:
      #   argocd.argoproj.io/sync-wave: "2"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: production 
      syncPolicy:
        syncOptions:
          - Validate=true
          - ServerSideApply=true
          - PrunePropagationPolicy=Foreground
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
      source:
        repoURL: *repo 
        targetRevision: main
        path: "{{path}}/overlays/prod"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
