apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/smipin/gitops.git
        revision: HEAD
        directories:
          - path: charts/*
            # exclude: charts/external-secrets
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/hook: skip
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: production 
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
      source:
        repoURL: https://github.com/zMynxx/turningpi2-k3s-gitops.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          # Helm values files for overriding values in the helm chart
          # The path is relative to the spec.source.path directory defined above
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
