---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging 
  namespace: cert-manager
spec:
  secretName: letsencrypt-staging 
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.tpi2.local"
  dnsNames:
  - "tpi2.local"
  - "*.tpi2.local"
