apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store
spec:
  provider:
    vault:
      # Calling local vault running in same cluster
      server: http://vault.vault.svc.cluster.local:8200
      path: argocd
      version: v2
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: approle
          # RoleID configured in the App Role authentication backend
          roleId: 8df399bd-3822-99f4-1ab4-98984ffb0afc
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: vault-secret
            key: secret-id
            namespace: vault
