apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &name minio

# Additonal resources to apply - do not worry about the order if you are using ArgoCD
resources:
  - namespace.yaml
  - tenant.yaml
  - minio-secrt.yaml
  - minio-user-0.yaml
  - minio-env-configuration.yaml
