apiVersion: v1
kind: Secret
metadata:
  name: minio-env-configuration
  namespace: minio
stringData:
  config.env: |-
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
    export CONSOLE_TLS_ENABLE="on"
type: Opaque
